# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.4
language: swift
podfile: Example/Podfile

cache:
    directories:
     - Carthage
     - Example/Pods

before_install:
- brew install carthage
- CarthageSupport/Scripts/Carthage/carthageInstallTests.command

script:
- bash checkBuild.command
- pod lib lint
- pod spec lint
